codecov:
  require_ci_to_pass: no
github_checks:
  annotations: false
coverage:
  status:
    project:
      default: false
      cli:
        paths:
         - "cmd/"
        target: 75%
        informational: true
      pkg:
        paths:
          - "pkg/"
        target: 75%
