name: Elemental CLI update

sources:
  goversion:
    name: Go version from go.mod
    kind: file
    spec:
      file: go.mod
      line: 3
    transformers:
    - trimprefix: "go "

targets:
  githubActions:
    kind: yaml
    sourceid: goversion
    spec:
      key: env.GO_VERSION
      files:
        - .github/workflows/build.yaml
        - .github/workflows/test.yaml
        - .github/workflows/docs.yaml
        - .github/workflows/lint.yaml
        - .github/workflows/release.yaml
  goDockerfile:
    name: "Update the value of ARG GO_VERSION in the Dockerfile"
    sourceID: goversion
    kind: dockerfile
    spec:
      file: Dockerfile
      instruction:
        keyword: "ARG"
        matcher: "GO_VERSION"
