install:
  # target is the only mandatory
  target: /dev/sda

  # basic disk configs for formatting
  firmware: efi
  partition-table: gpt

  # partitions setup, any missing value is taken from defaults
  partitions:
    oem:
      label: ALT_OEM
      size: 1024
      fs: ext4
    recovery:
      label: ALT_RECOVERY
      size: 1024
      fs: ext4

  # format disk or not
  no-format: false

  # use this iso as installation media (overwrites 'image' and 'recoveryImage' sources with iso contents)
  iso: https://my.domain.org/some/powerful.iso

  # main OS image
  system:
    label: COS_ACTIVE
    size: 1024
    fs: ext2
    source: oci://quay.io/costoolkit/green-releases:v1.2.3

  recovery:
    label: COS_SYSTEM
    size: 1024
    fs: ext2
    source: docker:quay.io/costoolkit/green-releases:latest


  passive-label: COS_PASSIVE
  cloud-init: "https://some.cloud-init.org/my-config-file"


cosign: true
cosign-key: myKey

# attempt a verify process
no-verify: false

# fail on cloud-init hooks errors
strict: false

# Additional paths for look for cloud-init files
cloud-init-paths:
  - "/some/path"
  
# reboot/power off when done
reboot: false
poweroff: false
