iso:
  rootfs:
    - system/cos
  uefi:
    - live/grub2-efi-image
  isoimage:
    - live/grub2
    - live/grub2-efi-image
    - recovery/cos-img
  label: "COS_LIVE"

# Raw disk creation values start


raw_disk:
  x86_64:
    repositories:
     - uri: quay.io/costoolkit/releases-green
    # which packages to install and the target to install them at
    packages:
      - name: system/grub2-efi-image
        target: efi
      - name: system/grub2-config
        target: root
      - name: system/grub2-artifacts
        target: root/grub2
      - name: recovery/cos-img
        target: root/cOS
  aarch64:
    repositories:
     - uri: quay.io/costoolkit/releases-green-arm64
    packages:
      - name: system/grub2-efi-image
        target: efi
      - name: system/grub2-config
        target: root
      - name: system/grub2-artifacts
        target: root/grub2
      - name: recovery/cos-img
        target: root/cOS
  odroid_c2:
    repositories:
     - uri: quay.io/costoolkit/releases-green-arm64
    packages:
      - name: system/grub2-efi-image
        target: efi
      - name: system/grub2-config
        target: root
      - name: system/grub2-artifacts
        target: root/grub2


# Raw disk creation values end

name: "cOS-0"
date: true
