name: Docker build and push
on:
  pull_request:
    paths:
      - Dockerfile
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Export tag
        id: export_tag
        run: |
          TAG=`git describe --tags 2>/dev/null || echo "v0.0.1"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/costoolkit/elemental
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,format=long
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          load: true # loads it locally, so it can be used from docker client
          target: elemental
          build-args: |
            ELEMENTAL_VERSION=${{ steps.export_tag.outputs.elemental_tag }}
            ELEMENTAL_COMMIT=${{ github.sha }}
      - name: Test docker image
        run: |
          # create a 30Gb file
          # qemu-img create -f raw disk.img 30G
          # mount loop device and get the device
          #LOOP=`sudo losetup -fP --show disk.img`
          # unfortunately loop devices are not properly refreshed under a container :/
          #docker run --privileged ${{ steps.meta.outputs.tags }} install --debug -d quay.io/costoolkit/releases-green:cos-system-0.8.6 $LOOP
          docker run ${{ steps.meta.outputs.tags }} version --long
