name: Docker build and push
on:
  pull_request:
    paths:
      - Dockerfile
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/costoolkit/elemental
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,format=long
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          load: true # loads it locally, so it can be used from docker client
          target: elemental
      - name: Test docker image
        run: |
          # create a 30Gb file
          dd if=/dev/zero of=loopbackfile.img bs=3000M count=10
          # mount loop device and get the device
          LOOP=`sudo losetup -fP --show loopbackfile.img`
          # run the install tot he loop device as a small test
          docker run --privileged ${{ steps.meta.outputs.tags }} install --debug $LOOP