name: Docker build and push
on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/docker.yaml
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install qemu-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils
      - name: Export tag
        id: export_tag
        run: |
          git describe --abbrev=0 --tags
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.1"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/costoolkit/elemental
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,format=short,prefix=${{ steps.export_tag.outputs.elemental_tag }}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          load: true # loads it locally, so it can be used from docker client
          # cache into GitHub actions cache, nice
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: elemental
          build-args: |
            ELEMENTAL_VERSION=${{ steps.export_tag.outputs.elemental_tag }}
            ELEMENTAL_COMMIT=${{ github.sha }}
      - name: Test elemental image version
        run: docker run ${{ steps.meta.outputs.tags }} version --long
      - name: Test elemental image install with --force-efi
        run: |
          # create a 30Gb file
          qemu-img create -f raw disk-efi.img 30G
          # mount loop device and get the device
          LOOP=`sudo losetup -fP --show disk-efi.img`
          docker run -v /dev/:/dev/ --privileged ${{ steps.meta.outputs.tags }} install --force-efi --debug -d quay.io/costoolkit/releases-green:cos-system-0.8.6 $LOOP
          sudo losetup -D $LOOP
          rm disk-efi.img
      - name: Test elemental image install
        run: |
          # create a 30Gb file
          qemu-img create -f raw disk.img 30G
          # mount loop device and get the device
          LOOP=`sudo losetup -fP --show disk.img`
          docker run -v /dev/:/dev/ --privileged ${{ steps.meta.outputs.tags }} install --debug -d quay.io/costoolkit/releases-green:cos-system-0.8.6 $LOOP
          sudo losetup -D $LOOP
          rm disk.img
      - name: Push image  # should be a free build as everything has been cached and loaded
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # cache into GitHub actions cache, nice
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: elemental
          build-args: |
            ELEMENTAL_VERSION=${{ steps.export_tag.outputs.elemental_tag }}
            ELEMENTAL_COMMIT=${{ github.sha }}
