name: Update cmd docs
on:
  push:
    branches:
      - main
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Build
        run: make build_docs
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          commit-message: "[auto] Update cmd docs"
          signoff: true
          title: "[auto] Update cmd docs"
          delete-branch: true
          reviewers: |
            itxaka
            davidcassany
            mudler
            mjura
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        if: ${{ steps.pr.outputs.pull-request-number }}
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}