name: Update cmd docs
on:
  push:
    branches:
      - main
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build
        run: make build_docs
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[auto] Update cmd docs"
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          push-to-fork: cos-ci-forks/elemental-cli
          signoff: true
          title: "[auto] Update cmd docs"
          delete-branch: true
          reviewers: |
            itxaka
            davidcassany
            mudler
            mjura