name: Update cmd docs
on:
  push:
    branches:
      - main
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-build-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-go-
      - name: Build
        run: make build-docs
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[auto] Update cmd docs"
          signoff: true
          branch-suffix: short-commit-hash
          title: "[auto] Update cmd docs"
          delete-branch: true
          reviewers: |
            itxaka
            davidcassany
            mudler
            mjura